version: "3"
networks:
  nocobase:
    driver: bridge
services:
  app:
    image: nocobase/nocobase:1.0.0-alpha.6
    networks:
      - nocobase
    environment:
      - APP_KEY=your-secret-key # Replace it with your own app key
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"