export const styles = {
  main: {
    padding: '1rem',
    display: 'flex',
    flexFlow: 'column',
    height: '70%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  hero: {
    padding: '1rem',
    display: 'flex',
    flexFlow: 'column',
    height: '70%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sidebar: {
    width: '15%',
    borderRight: '1px solid #E3E3E3',
    padding: '1rem',
    display: 'flex',
    flexFlow: 'column',
    gap: '1rem',
  },
  sidebarHeading: {
    fontSize: '20px',
    fontWeight: '500',
    fontFamily: 'Roboto',
    lineHeight: '28px',
  },
  heading: {
    color: 'black',
    fontSize: '1.5rem',
    marginBottom: '0.5rem',
  },
  byline: {
    color: 'gray',
    fontSize: '0.8rem',
    display: 'flex',
    justifyContent: 'center',
  },
  suggestionHolder: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gridTemplateRows: 'repeat(2, 1fr)',
    gap: '10px',
    marginTop: '1rem',
    marginBottom: '2rem',
  },
  promptSuggestion: {
    backgroundColor: 'whitesmoke',
    padding: '0.8rem',
    cursor: 'pointer',
    width: '28rem',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  userInput: {
    display: 'flex',
    margin: '1rem',
  },
  textBox: {
    height: '3rem',
    borderRight: '0px',
    width: '30rem',
    paddingLeft: '1rem',
    outline: 'none',
  },
  button: {
    backgroundColor: 'black',
    color: 'white',
    height: '3rem',
    width: '6rem',
    cursor: 'pointer',
  },
  newChatbutton: {
    backgroundColor: 'black',
    color: 'white',
    padding: '0.25rem',
    borderRadius: '4px',
    width: '100%',
    cursor: 'pointer',
  },
  chatile: {
    padding: '0.5rem',
    borderRadius: '4px',
    border: '1px solid gainsboro',
    width: '100%',
    cursor: 'pointer',
    display: 'flex',
    gap: '0.2rem',
    alignItems: 'center',
  },
  chatileText: {
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '90%',
  },
  chartholder: {
    display: 'flex',
    flexFlow: 'column',
    gap: '0.25rem',
  },
  footer: {
    marginTop: '4rem',
    display: 'none',
  },
  footerMessage: {
    display: 'flex',
    gap: '0.5rem',
    backgroundColor: '#E5EFFD',
    border: '1px solid #B5D1FA',
    color: '#395263',
    package: '0.8rem',
  },
  question: {
    marginTop: '2rem',
    border: '1px solid gainsboro',
    backgroundColor: 'whitesmoke',
    borderRadius: '0.5rem',
    padding: '1rem',
    display: 'inline-flex',
    maxWidth: '100%',
    gap: '4px',
  },
  questionHolder: {
    display: 'flex',
    flexFlow: 'row',
    justifyContent: 'flex-end',
  },
};
