name: Deploy to Server

on:
  push:
    branches:
      - original  # Change to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add GitHub to known_hosts
      run: |
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Execute remote commands
      run: |
        ssh -o StrictHostKeyChecking=no root@45.77.146.40 << 'EOF'
          cd rantir-cloud-go
          git pull origin original
          yarn build
          yarn nocobase pm2-stop
          yarn start -d
        EOF
